@startuml Direct Integration System Diagram
[DJI M300] as dji
[Payload SDK Adapter Board] as sdk_adapter
[Up Core] as OBC
[Software Defined Radio] as SDR
[Low Noise Amplifier] as LNA
[VHF Antenna] as payload_antenna
[USB Storage] as storage
[Ground Control Station] as gcs

interface "DJI Skyport V2 Adapter" as skyport
interface "5V2A" as payload_5v2a
interface "Up Core.USB 3.0" as obc_usb3
interface "3v3 UART" as payload_uart
interface "Up Core.USB 2.0" as obc_usb2
interface "WiFi" as obc_wifi

dji --> skyport
skyport --> sdk_adapter
sdk_adapter --> payload_5v2a
payload_5v2a --> OBC
payload_5v2a --> LNA

payload_antenna -> LNA
LNA -> SDR
SDR -> obc_usb3
obc_usb3 -> OBC
OBC <-> obc_usb2
obc_usb2 -> storage

sdk_adapter <--> payload_uart
payload_uart <--> obc_usb2

OBC <--> obc_wifi
obc_wifi <--> gcs
@enduml

@startuml Independent Payload System Diagram
[DJI M300] as dji
[Payload SDK Adapter Board] as sdk_adapter
[Up Core] as OBC
[Software Defined Radio] as SDR
[Low Noise Amplifier] as LNA
[VHF Antenna] as payload_antenna
[USB Storage] as storage
[Ground Control Station] as gcs
[Payload GPS] as payload_gps

interface "DJI Skyport V2 Adapter" as skyport
interface "5V2A" as payload_5v2a
interface "Up Core.USB 3.0" as obc_usb3
interface "3v3 UART" as payload_uart
interface "Up Core.USB 2.0" as obc_usb2
interface "WiFi" as obc_wifi

dji --> skyport
skyport --> sdk_adapter
sdk_adapter --> payload_5v2a
payload_5v2a --> OBC
payload_5v2a --> LNA

payload_antenna -> LNA
LNA -> SDR
SDR -> obc_usb3
obc_usb3 -> OBC
OBC <-> obc_usb2
obc_usb2 -> storage

sdk_adapter <--> payload_uart
payload_gps <--> obc_usb2

OBC <--> obc_wifi
obc_wifi <--> gcs
@enduml

@startuml Radio Collar Tracker: TCI Wiring Diagram
[Software Defined Radio] as SDR
[On-Board Computer] as OBC
[VHF Antenna] as ANT
[LNA] as LNA
[12V to 5V Regulator] as PRIMARY_REG
[DJI Skyport V2 Adapter] as SKYPORT
interface "Wifi Antenna" as WIFI_ANT
component "UI Board" {
    port p1
    [UI Board] as UIB
    [Data Drive] as USB_DATA
    [GPS Receiver] as GPS
    p1 --> UIB
    UIB --> USB_DATA : USB 2.0 A to USB Device
    UIB --> GPS : 6 pin cable
}
[SiK Radio] as radio

component "UI Board Cable"{
    portin UIB_IN
    portout USB3_out
    portout UIB_OUT
    [USB Hub] as hub
    interface USB1_in
    interface USB2_in
    interface UART_in
    interface USB1_out
    interface USB2_out
    interface UART_out

    UIB_IN --> USB1_in
    UIB_IN --> USB2_in
    UIB_IN --> UART_in
    USB1_out --> UIB_OUT
    USB2_out --> UIB_OUT
    UART_out --> UIB_OUT
    USB2_in --> hub
    hub --> USB3_out
    hub --> USB2_out
    USB1_in --> USB1_out
    UART_in --> UART_out
}

OBC --> SDR : USB 3.0 A to USB 3.0 micro B
SDR --> LNA : SMA-M to SMA-M
LNA --> ANT : SMA-M to SMA-M
OBC --> WIFI_ANT : uFl to RP-SMA-M
OBC --> UIB_IN : 11 pos cable
UIB_OUT --> p1
SKYPORT --> PRIMARY_REG : XT30 to device
PRIMARY_REG --> OBC : device to 5.5mm Barrel
SKYPORT --> LNA : XT30 to device
USB3_out --> radio
@enduml